"""changed PoemTone and PoemFeature Models

Revision ID: 02749bee0611
Revises: 5252f4a95fb6
Create Date: 2018-12-07 14:01:09.378740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02749bee0611'
down_revision = '5252f4a95fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar',
    sa.Column('poem_a_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poem_b_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['poem_a_id'], ['poem.id'], name='similar_poem_a_id_fkey'),
    sa.ForeignKeyConstraint(['poem_b_id'], ['poem.id'], name='similar_poem_b_id_fkey')
    )
    # ### end Alembic commands ###
