"""changes

Revision ID: 2bd72977283f
Revises: d9f96d351d86
Create Date: 2018-12-02 22:39:09.276165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd72977283f'
down_revision = 'd9f96d351d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'poem', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poem', type_='foreignkey')
    op.drop_column('poem', 'user_id')
    # ### end Alembic commands ###
