"""changed PoemTone and PoemFeature Models

Revision ID: 5252f4a95fb6
Revises: 63dba0f9b46a
Create Date: 2018-12-07 01:46:50.810662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5252f4a95fb6'
down_revision = '63dba0f9b46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar',
    sa.Column('poem_a_id', sa.Integer(), nullable=True),
    sa.Column('poem_b_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poem_a_id'], ['poem.id'], ),
    sa.ForeignKeyConstraint(['poem_b_id'], ['poem.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar')
    # ### end Alembic commands ###
