"""PoemFeature table

Revision ID: 627e42254fab
Revises: 84a82db8b903
Create Date: 2018-12-02 03:12:27.679468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627e42254fab'
down_revision = '84a82db8b903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('close_poem', sa.Integer(), nullable=True),
    sa.Column('top_topic', sa.Integer(), nullable=True),
    sa.Column('poem_id', sa.Integer(), nullable=True),
    sa.Column('num_lines', sa.Integer(), nullable=True),
    sa.Column('num_words', sa.Integer(), nullable=True),
    sa.Column('word_size', sa.Float(), nullable=True),
    sa.Column('width_in_char', sa.Float(), nullable=True),
    sa.Column('repetition_score', sa.Float(), nullable=True),
    sa.Column('obscurity_score', sa.Float(), nullable=True),
    sa.Column('sentence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], ['poem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poem_feature')
    # ### end Alembic commands ###
