"""changes

Revision ID: 67276368f57c
Revises: bfb61a0e9867
Create Date: 2018-12-05 14:49:27.197385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67276368f57c'
down_revision = 'bfb61a0e9867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem', sa.Column('times_liked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poem', 'times_liked')
    # ### end Alembic commands ###
