"""changed PoemTone and PoemFeature Models

Revision ID: 69e61083cfe7
Revises: 67276368f57c
Create Date: 2018-12-06 19:02:09.690827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e61083cfe7'
down_revision = '67276368f57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moods',
    sa.Column('poem_tone_id', sa.Integer(), nullable=True),
    sa.Column('poem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], ['poem.id'], ),
    sa.ForeignKeyConstraint(['poem_tone_id'], ['poem_tone.id'], )
    )
    op.add_column('poem', sa.Column('mood', sa.String(), nullable=True))
    op.drop_column('poem', 'times_liked')
    op.drop_constraint('poem_feature_poem_id_fkey', 'poem_feature', type_='foreignkey')
    op.drop_column('poem_feature', 'poem_id')
    op.drop_constraint('poem_tone_poemfeature_id_fkey', 'poem_tone', type_='foreignkey')
    op.drop_column('poem_tone', 'poemfeature_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem_tone', sa.Column('poemfeature_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('poem_tone_poemfeature_id_fkey', 'poem_tone', 'poem_feature', ['poemfeature_id'], ['id'])
    op.add_column('poem_feature', sa.Column('poem_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('poem_feature_poem_id_fkey', 'poem_feature', 'poem', ['poem_id'], ['id'])
    op.add_column('poem', sa.Column('times_liked', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('poem', 'mood')
    op.drop_table('moods')
    # ### end Alembic commands ###
