"""changes

Revision ID: 8385bf5a1aac
Revises: 2bd72977283f
Create Date: 2018-12-03 23:15:17.359620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8385bf5a1aac'
down_revision = '2bd72977283f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem_feature', sa.Column('times_liked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poem_feature', 'times_liked')
    # ### end Alembic commands ###
