"""Poem table

Revision ID: 84a82db8b903
Revises: ffb23daa8ffc
Create Date: 2018-12-02 03:08:30.359235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a82db8b903'
down_revision = 'ffb23daa8ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('text', sa.String(length=2500), nullable=True),
    sa.Column('poet', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=60), nullable=True),
    sa.Column('tags', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poem')
    # ### end Alembic commands ###
