"""changes

Revision ID: bfb61a0e9867
Revises: 8385bf5a1aac
Create Date: 2018-12-04 23:56:09.751299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb61a0e9867'
down_revision = '8385bf5a1aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], ['poem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_constraint('poem_user_id_fkey', 'poem', type_='foreignkey')
    op.drop_column('poem', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('poem_user_id_fkey', 'poem', 'user', ['user_id'], ['id'])
    op.drop_table('likes')
    # ### end Alembic commands ###
