"""added many to many db model for poems (recommended feature

Revision ID: c2a0b13ed1b5
Revises: 02749bee0611
Create Date: 2018-12-07 14:49:58.285388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a0b13ed1b5'
down_revision = '02749bee0611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem_to_poem',
    sa.Column('poem_a_id', sa.Integer(), nullable=False),
    sa.Column('poem_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poem_a_id'], ['poem.id'], ),
    sa.ForeignKeyConstraint(['poem_b_id'], ['poem.id'], ),
    sa.PrimaryKeyConstraint('poem_a_id', 'poem_b_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poem_to_poem')
    # ### end Alembic commands ###
