"""PoemTone table, changes

Revision ID: d9f96d351d86
Revises: 627e42254fab
Create Date: 2018-12-02 03:44:28.752381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f96d351d86'
down_revision = '627e42254fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem_tone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tone_confidence', sa.Float(), nullable=True),
    sa.Column('poemfeature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poemfeature_id'], ['poem_feature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poem_tone')
    # ### end Alembic commands ###
